# PySNMP SMI module. Autogenerated from smidump -f python RFC1155-SMI
# by libsmi2pysnmp-0.1.3
# Python version sys.version_info(major=2, minor=7, micro=11, releaselevel='final', serial=0)
# pylint:disable=C0302

mibBuilder = mibBuilder  # pylint:disable=undefined-variable,used-before-assignment

# Imports

(Integer, ObjectIdentifier, OctetString, ) = mibBuilder.importSymbols("ASN1", "Integer", "ObjectIdentifier", "OctetString")
(NamedValues, ) = mibBuilder.importSymbols("ASN1-ENUMERATION", "NamedValues")
(ConstraintsIntersection, ConstraintsUnion, SingleValueConstraint, ValueRangeConstraint, ValueSizeConstraint, ) = mibBuilder.importSymbols("ASN1-REFINEMENT", "ConstraintsIntersection", "ConstraintsUnion", "SingleValueConstraint", "ValueRangeConstraint", "ValueSizeConstraint")
(Bits, Integer32, MibIdentifier, TimeTicks, ) = mibBuilder.importSymbols("SNMPv2-SMI", "Bits", "Integer32", "MibIdentifier", "TimeTicks")
(TimeTicks, Unsigned32, ) = mibBuilder.importSymbols("SNMPv2-TC", "TimeTicks", "Unsigned32")

# Types


class Counter(Unsigned32):  # pylint:disable=too-few-public-methods
	subtypeSpec = Unsigned32.subtypeSpec + ValueRangeConstraint(0, 4294967295)


class Gauge(Unsigned32):  # pylint:disable=too-few-public-methods
	subtypeSpec = Unsigned32.subtypeSpec + ValueRangeConstraint(0, 4294967295)


class IpAddress(OctetString):  # pylint:disable=too-few-public-methods
	subtypeSpec = OctetString.subtypeSpec + ValueSizeConstraint(4, 4)
	fixedLength = 4


class ObjectName(ObjectIdentifier):  # pylint:disable=too-few-public-methods
	pass


class Opaque(OctetString):  # pylint:disable=too-few-public-methods
	pass


class NetworkAddress(IpAddress):  # pylint:disable=too-few-public-methods
	pass


# Exports

# Types
mibBuilder.exportSymbols("RFC1155-SMI", Counter=Counter, Gauge=Gauge, IpAddress=IpAddress, ObjectName=ObjectName, Opaque=Opaque, NetworkAddress=NetworkAddress)
