# PySNMP SMI module. Autogenerated from smidump -f python RUCKUS-SCG-SYSTEM-MIB
# by libsmi2pysnmp-0.1.3 at Thu May 19 15:23:57 2016,
# Python version sys.version_info(major=2, minor=7, micro=11, releaselevel='final', serial=0)

# Imports

( Integer, ObjectIdentifier, OctetString, ) = mibBuilder.importSymbols("ASN1", "Integer", "ObjectIdentifier", "OctetString")
( NamedValues, ) = mibBuilder.importSymbols("ASN1-ENUMERATION", "NamedValues")
( ConstraintsIntersection, ConstraintsUnion, SingleValueConstraint, ValueRangeConstraint, ValueSizeConstraint, ) = mibBuilder.importSymbols("ASN1-REFINEMENT", "ConstraintsIntersection", "ConstraintsUnion", "SingleValueConstraint", "ValueRangeConstraint", "ValueSizeConstraint")
( InterfaceIndex, ifIndex, ) = mibBuilder.importSymbols("IF-MIB", "InterfaceIndex", "ifIndex")
( ruckusSCGSystemModule, ) = mibBuilder.importSymbols("RUCKUS-ROOT-MIB", "ruckusSCGSystemModule")
( ObjectGroup, ) = mibBuilder.importSymbols("SNMPv2-CONF", "ObjectGroup")
( Bits, Counter32, Counter64, Integer32, Integer32, IpAddress, ModuleIdentity, MibIdentifier, MibScalar, MibTable, MibTableRow, MibTableColumn, TimeTicks, Unsigned32, ) = mibBuilder.importSymbols("SNMPv2-SMI", "Bits", "Counter32", "Counter64", "Integer32", "Integer32", "IpAddress", "ModuleIdentity", "MibIdentifier", "MibScalar", "MibTable", "MibTableRow", "MibTableColumn", "TimeTicks", "Unsigned32")
( DisplayString, MacAddress, RowStatus, TruthValue, ) = mibBuilder.importSymbols("SNMPv2-TC", "DisplayString", "MacAddress", "RowStatus", "TruthValue")

# Objects

ruckusSystemMIB = ModuleIdentity((1, 3, 6, 1, 4, 1, 25053, 1, 3, 1, 1)).setRevisions(("2014-05-19 11:00",))
if mibBuilder.loadTexts: ruckusSystemMIB.setOrganization("Ruckus Wireless, Inc.")
if mibBuilder.loadTexts: ruckusSystemMIB.setContactInfo("Ruckus Wireless, Inc.\n\n350 West Java Dr.\nSunnyvale, CA 94089\nUSA\n\nT: +1 (650) 265-4200\nF: +1 (408) 738-2065\nEMail: info@ruckuswireless.com\nWeb: www.ruckuswireless.com")
if mibBuilder.loadTexts: ruckusSystemMIB.setDescription("Ruckus System mib")
ruckusSystemObjects = MibIdentifier((1, 3, 6, 1, 4, 1, 25053, 1, 3, 1, 1, 1))
ruckusSystemStats = MibIdentifier((1, 3, 6, 1, 4, 1, 25053, 1, 3, 1, 1, 1, 15))
ruckusSystemStatsNumAP = MibScalar((1, 3, 6, 1, 4, 1, 25053, 1, 3, 1, 1, 1, 15, 1), Unsigned32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: ruckusSystemStatsNumAP.setDescription("Number of AP")
ruckusSystemStatsNumSta = MibScalar((1, 3, 6, 1, 4, 1, 25053, 1, 3, 1, 1, 1, 15, 2), Unsigned32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: ruckusSystemStatsNumSta.setDescription("Number of associated client devices")
ruckusSystemStatsWLANTotalRxPkts = MibScalar((1, 3, 6, 1, 4, 1, 25053, 1, 3, 1, 1, 1, 15, 5), Counter64()).setMaxAccess("readonly")
if mibBuilder.loadTexts: ruckusSystemStatsWLANTotalRxPkts.setDescription("Total received packets of wireless interfaces")
ruckusSystemStatsWLANTotalRxBytes = MibScalar((1, 3, 6, 1, 4, 1, 25053, 1, 3, 1, 1, 1, 15, 6), Counter64()).setMaxAccess("readonly")
if mibBuilder.loadTexts: ruckusSystemStatsWLANTotalRxBytes.setDescription("Total received bytes of wireless interfaces")
ruckusSystemStatsWLANTotalRxMulticast = MibScalar((1, 3, 6, 1, 4, 1, 25053, 1, 3, 1, 1, 1, 15, 7), Counter64()).setMaxAccess("readonly")
if mibBuilder.loadTexts: ruckusSystemStatsWLANTotalRxMulticast.setDescription("Total received multicast packets of wireless interfaces")
ruckusSystemStatsWLANTotalTxPkts = MibScalar((1, 3, 6, 1, 4, 1, 25053, 1, 3, 1, 1, 1, 15, 8), Counter64()).setMaxAccess("readonly")
if mibBuilder.loadTexts: ruckusSystemStatsWLANTotalTxPkts.setDescription("Total transmitted packets of wireless interfaces")
ruckusSystemStatsWLANTotalTxBytes = MibScalar((1, 3, 6, 1, 4, 1, 25053, 1, 3, 1, 1, 1, 15, 9), Counter64()).setMaxAccess("readonly")
if mibBuilder.loadTexts: ruckusSystemStatsWLANTotalTxBytes.setDescription("Total transmitted bytes of wireless interfaces")
ruckusSystemStatsWLANTotalTxMulticast = MibScalar((1, 3, 6, 1, 4, 1, 25053, 1, 3, 1, 1, 1, 15, 10), Counter64()).setMaxAccess("readonly")
if mibBuilder.loadTexts: ruckusSystemStatsWLANTotalTxMulticast.setDescription("Total transmitted multicast packets of wireless interfaces")
ruckusSystemStatsWLANTotalTxFail = MibScalar((1, 3, 6, 1, 4, 1, 25053, 1, 3, 1, 1, 1, 15, 11), Counter64()).setMaxAccess("readonly")
if mibBuilder.loadTexts: ruckusSystemStatsWLANTotalTxFail.setDescription("Total transmitted fail packets of wireless interfaces")
ruckusSystemStatsWLANTotalTxRetry = MibScalar((1, 3, 6, 1, 4, 1, 25053, 1, 3, 1, 1, 1, 15, 12), Counter64()).setMaxAccess("readonly")
if mibBuilder.loadTexts: ruckusSystemStatsWLANTotalTxRetry.setDescription("Total transmitted retry packets of wireless interfaces")
ruckusSystemStatsSerialNumber = MibScalar((1, 3, 6, 1, 4, 1, 25053, 1, 3, 1, 1, 1, 15, 13), DisplayString()).setMaxAccess("readonly")
if mibBuilder.loadTexts: ruckusSystemStatsSerialNumber.setDescription("Serial Number")

# Augmentions

# Exports

# Module identity
mibBuilder.exportSymbols("RUCKUS-SCG-SYSTEM-MIB", PYSNMP_MODULE_ID=ruckusSystemMIB)

# Objects
mibBuilder.exportSymbols("RUCKUS-SCG-SYSTEM-MIB", ruckusSystemMIB=ruckusSystemMIB, ruckusSystemObjects=ruckusSystemObjects, ruckusSystemStats=ruckusSystemStats, ruckusSystemStatsNumAP=ruckusSystemStatsNumAP, ruckusSystemStatsNumSta=ruckusSystemStatsNumSta, ruckusSystemStatsWLANTotalRxPkts=ruckusSystemStatsWLANTotalRxPkts, ruckusSystemStatsWLANTotalRxBytes=ruckusSystemStatsWLANTotalRxBytes, ruckusSystemStatsWLANTotalRxMulticast=ruckusSystemStatsWLANTotalRxMulticast, ruckusSystemStatsWLANTotalTxPkts=ruckusSystemStatsWLANTotalTxPkts, ruckusSystemStatsWLANTotalTxBytes=ruckusSystemStatsWLANTotalTxBytes, ruckusSystemStatsWLANTotalTxMulticast=ruckusSystemStatsWLANTotalTxMulticast, ruckusSystemStatsWLANTotalTxFail=ruckusSystemStatsWLANTotalTxFail, ruckusSystemStatsWLANTotalTxRetry=ruckusSystemStatsWLANTotalTxRetry, ruckusSystemStatsSerialNumber=ruckusSystemStatsSerialNumber)

